version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ALEMBIC_PORT}:${ALEMBIC_PORT}"
    command:
      - 'php'
      - '-S'
      - '[::]:${ALEMBIC_PORT}'
      - '-t'
      - '/var/www/html'