"""empty message

Revision ID: e96f2ffb1047
Revises: 83cfc6c0eb47
Create Date: 2023-01-08 01:27:33.369497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96f2ffb1047'
down_revision = '83cfc6c0eb47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_index('ix_user_login', table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_column('user', 'login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index('ix_user_login', 'user', ['login'], unique=False)
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
